# Site settings
title: Coercionist Under a Blue Sky
description: 'When two parties involved in its most ordinary cases' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/onthecouch.github.io" # the subpath of your site, e.g. /blog
url: "https://www.snawf.my.id" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/HD-logo-full.svg"
logo-icon: "/assets/img/branding/HD-symbol.svg"
logo-icon-SEO: "/assets/img/branding/HD-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "on"

logo-dark: "/assets/img/branding/HD-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Henry Dennis # add your name
author-pic: dp.jpg
about-author: Sys Admin, Professional Designer. A personal static site for documented what I have rarely done at work, might sometimes posting about my design. 15+ years of experience.

# Contact links
email: pm@snawf.my.id # Add your Email address
phone: # Add your Phone number
website: https://www.snawf.my.id # Add your website
linkedin: henrydns # Add your Linkedin handle
github: onthecouch # Add your Github handle
twitter: '@henrydns' # Add your Twitter handle

# Tracker
analytics: UA-219241214-1 
fbadmin: #

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
